classdef TetrahedronLaplaceTest
    % =========================================================================
    % Class: TetrahedronLaplaceTest
    % -------------------------------------------------------------------------
    % Description:
    %     This class provides a framework for verifying the *Poisson–Laplace
    %     behavior* of the gravitational potential generated by a homogeneous
    %     tetrahedron. It numerically evaluates the Laplacian (∇²V) of the
    %     analytic potential across a user-defined plane, confirming:
    %
    %         ∇²V = -4πGσ   → Inside the tetrahedron  (Poisson equation)
    %         ∇²V =  0       → Outside the tetrahedron (Laplace equation)
    %
    %     The class internally calls the analytic potential solver
    %     (`TetrahedronPotentialCalculatorOOP`) for each grid point and uses
    %     finite-difference approximation for the second derivatives.
    %
    % Reference:
    %     Periyandy, T. & Bevis, M. (2025)
    %     “The Gravitational Potential Inside, On and Outside of a
    %      Homogeneous Tetrahedron.”
    %
    % Authors:
    %     Thunendran Periyandy  (corresponding author)
    %     Michael Bevis
    %
    % Date:    July 31, 2025
    % Version: 1.0
    % =========================================================================
    
    properties
        % ---------------------------------------------------------------------
        % Vertices of the tetrahedron (1×3 vectors)
        % ---------------------------------------------------------------------
        A
        B
        C
        D
        
        % ---------------------------------------------------------------------
        % Physical constants
        % ---------------------------------------------------------------------
        G = 1        % Gravitational constant (default = 1)
        sigma = 1    % Surface mass density (default = 1)
    end
    
    % ======================================================================
    % Constructor
    % ======================================================================
    methods
        function obj = TetrahedronLaplaceTest(A,B,C,D,G,sigma)
            % -----------------------------------------------------------------
            % Constructor
            %
            % Initializes a Laplace test object using the tetrahedron’s vertex
            % coordinates and optional physical parameters.
            %
            % Usage:
            %   obj = TetrahedronLaplaceTest(A,B,C,D)
            %   obj = TetrahedronLaplaceTest(A,B,C,D,G,sigma)
            %
            % Inputs:
            %   A,B,C,D : 1×3 vectors — vertex coordinates
            %   G       : gravitational constant (default = 1)
            %   sigma   : surface density (default = 1)
            %
            % Output:
            %   obj : TetrahedronLaplaceTest instance
            % -----------------------------------------------------------------
            
            if nargin >= 4
                obj.A = A; obj.B = B; obj.C = C; obj.D = D;
            end
            if nargin >= 5, obj.G = G; end
            if nargin >= 6, obj.sigma = sigma; end
        end
        
    % ======================================================================
    % Potential and Laplacian Computation Methods
    % ======================================================================
        function val = phi(obj, x, y, z)
            % -----------------------------------------------------------------
            % phi — Compute gravitational potential at a single point
            %
            % Evaluates the analytic potential V(x, y, z) for the tetrahedron
            % by creating a local instance of `TetrahedronPotentialCalculatorOOP`.
            %
            % Usage:
            %   val = obj.phi(x, y, z)
            %
            % Inputs:
            %   x, y, z : Scalars — coordinates of the evaluation point
            %
            % Output:
            %   val : Scalar — potential value at (x, y, z)
            % -----------------------------------------------------------------
            
            calc = TetrahedronPotentialCalculatorOOP( ...
                        obj.A, obj.B, obj.C, obj.D, [x,y,z], obj.G, obj.sigma);
            val = - calc.compute();
        end
        
        function lap_val = laplacian(obj, f, x, y, z, h)
            % -----------------------------------------------------------------
            % laplacian — Numerical Laplacian (∇²V) via central differences
            %
            % Approximates the second spatial derivatives of a scalar field f
            % using symmetric finite differences along x, y, and z directions.
            %
            % Usage:
            %   lap_val = obj.laplacian(f, x, y, z)
            %   lap_val = obj.laplacian(f, x, y, z, h)
            %
            % Inputs:
            %   f   : Function handle — the potential function (e.g. @obj.phi)
            %   x,y,z : Scalars — evaluation point coordinates
            %   h   : Step size (default = 1e-4)
            %
            % Output:
            %   lap_val : Scalar — numerical estimate of ∇²f(x, y, z)
            %
            % Notes:
            %   Smaller h increases precision but also computational cost.
            % -----------------------------------------------------------------
            
            if nargin < 6
                h = 1e-4;
            end
            
            lap_val = (f(x+h,y,z) - 2*f(x,y,z) + f(x-h,y,z)) / h^2 + ...
                      (f(x,y+h,z) - 2*f(x,y,z) + f(x,y-h,z)) / h^2 + ...
                      (f(x,y,z+h) - 2*f(x,y,z) + f(x,y,z-h)) / h^2;
        end
        
        function [X,Y,lap_grid] = compute_laplacian_grid(obj, z_plane, x_range, y_range, resolution)
            % -----------------------------------------------------------------
            % compute_laplacian_grid — Evaluate ∇²V on a 2D plane
            %
            % Numerically computes the Laplacian of the gravitational potential
            % over a regular (x,y) grid at a fixed z-plane.
            %
            % Usage:
            %   [X, Y, lap_grid] = obj.compute_laplacian_grid(z_plane, x_range, y_range)
            %   [X, Y, lap_grid] = obj.compute_laplacian_grid(z_plane, x_range, y_range, resolution)
            %
            % Inputs:
            %   z_plane    : Scalar — z-coordinate of the analysis plane
            %   x_range    : [xmin xmax] — range of x-values
            %   y_range    : [ymin ymax] — range of y-values
            %   resolution : Integer (default = 200) — grid density
            %
            % Outputs:
            %   X, Y       : Meshgrid coordinates (for plotting)
            %   lap_grid   : Matrix of Laplacian values (same dimensions as X, Y)
            %
            % Notes:
            %   - Each grid point calls the analytical solver to evaluate φ(x,y,z),
            %     followed by finite differencing to estimate ∇²φ.
            %   - High resolution improves spatial smoothness at higher cost.
            % -----------------------------------------------------------------
            
            if nargin < 6
                resolution = 200;
            end
            
            x_vals = linspace(x_range(1), x_range(2), resolution);
            y_vals = linspace(y_range(1), y_range(2), resolution);
            [X, Y] = meshgrid(x_vals, y_vals);
            Z = ones(size(X)) * z_plane;
            
            lap_grid = zeros(size(X));
            
            for i = 1:resolution
                for j = 1:resolution
                    lap_grid(i,j) = obj.laplacian(@(x,y,z)obj.phi(x,y,z), ...
                                                  X(i,j), Y(i,j), Z(i,j));
                end
            end
        end
    end
end
